log:
  level: debug
  disable_sentry: true

db:
  url: postgresql://shortener_user:shortener_password@db:5432/url_shortener_db

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: url-shortener-svc
  service_port: 80
