version: '3'
services:
  db:
    image: postgres:13
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: shortener_user
      POSTGRES_PASSWORD: shortener_password
      POSTGRES_DB: url_shortener_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - url_shortener_network

  nginx:
    image: nginx:latest
    container_name: url_shortener_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - url_shortener_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    command: ["run", "service"]
    environment:
      - KV_VIPER_FILE=/app/config.yaml
    volumes:
      - .:/app
      - ./config.yaml:/app/config.yaml
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - url_shortener_network

volumes:
  pgdata:

networks:
  url_shortener_network:
